# yaml-language-server: $schema=https://json.schemastore.org/openapi-3.0.json

openapi: 3.0.1
info:
  title: 玄武門之變解謎遊戲
  version: 1.0.0
  description: |
    這是一款基於唐代歷史的解謎遊戲，提供多層次的互動謎題。
servers:
  - url: https://chang5763.github.io/ai-plugin
paths:
  /solve-puzzle:
    post:
      summary: 提交玩家的解謎答案
      operationId: solvePuzzle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                puzzleId:
                  type: string
                  description: 謎題的唯一標識符
                answer:
                  type: string
                  description: 玩家提交的答案
      responses:
        '200':
          description: 玩家答案的驗證結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  correct:
                    type: boolean
                    description: 答案是否正確
                  message:
                    type: string
                    description: 提供的反饋信息
